import * as THREE from 'three';
import { makeGame, run } from './helpers.js';
const g = makeGame();
const W = g.game.world;
const rail = g.game.rails.rails.find(r=>r.id===42);
const s0 = 4;
const p0 = rail.pointAt(s0,new THREE.Vector3()), t = rail.tangentAt(s0,new THREE.Vector3()); t.y=0; t.normalize();
const side = new THREE.Vector3(-t.z,0,t.x);
const start = p0.clone().addScaledVector(side, 1.1);
start.y = W.terrain.heightAt(start.x,start.z)+0.05;
g.player.placeAt(start, Math.atan2(t.x,t.z));
run(g, 0.1);
g.player.vel.set(t.x*10,0,t.z*10);
g.input.moveY = 1;
run(g, 0.1, {dir:[t.x,t.z]});
g.input.moveY = -1; // pull back -> skid
run(g, 0.05, {dir:[t.x,t.z]});
console.log('skidding before grab:', g.player.skidding, 'state', g.player.state, 'hs', g.player.hspeed.toFixed(2));
g.input.tap('grab');
run(g, 0.05, {dir:[t.x,t.z]});
console.log('after grab: state', g.player.state, 'skidding flag', g.player.skidding);
g.input.moveY = 1;
run(g, 0.4, {dir:[t.x,t.z]});
g.input.tap('jump');
run(g, 0.05, {dir:[t.x,t.z]});
console.log('jumped off: state', g.player.state, 'hs', g.player.hspeed.toFixed(2), 'skidding', g.player.skidding);
let landed=null; const samples=[];
run(g, 1.6, {dir:[t.x,t.z], each:(c,tt)=>{ if (!landed && c.player.state==='ground'){ landed={t:tt, hs:c.player.hspeed}; } if (landed && samples.length<8 && Math.round(tt*60)%3===0) samples.push(`${c.player.hspeed.toFixed(2)}${c.player.skidding?'(skid)':''}`); }});
console.log('landed at hs', landed && landed.hs.toFixed(2), 'speeds after landing (every 50ms):', samples.join(' '));
console.log('skid events:', g.log.filter(e=>e.name==='skid').length, 'states:', g.log.filter(e=>e.name==='state').map(e=>e.data.to).join('>'));
