import * as THREE from 'three';
import { makeGame, run } from './helpers.js';
import { ComboSystem } from '../src/game/tricks.js';
const V=(x,y,z)=>new THREE.Vector3(x,y,z);
const g = makeGame();
const game = g.game;
game.settings = { scoring: 'full' }; game.save = { gaps: [] }; game.writeSave = () => {}; game.level = g.level; game.player = g.player; game.time = 0;
const combo = new ComboSystem(game);
const step = (sec, dir=[1,0]) => run(g, sec, { dir, each: (c) => { game.time = c.input.time; combo.update(1/60); } });
const ground=(x,z)=>game.world.terrain.heightAt(x,z);
g.player.placeAt(V(40, ground(40,34)+0.1, 34), 0);
step(0.3);
g.input.moveY = 1; step(1.0);
g.input.press('slide'); step(0.6);
console.log('slid, slideDist=', combo.slideDist.toFixed(2), 'sliding', g.player.sliding);
g.input.tap('jump'); step(0.05); g.input.release('slide');
step(1.2);
console.log('after long jump + landing: state', g.player.state, 'slideDist still', combo.slideDist.toFixed(2));
step(1.0);
// short tap slide of ~0.15 s
g.input.press('slide'); step(0.15); g.input.release('slide'); step(0.3);
const ps = g.log.filter(e=>e.name==='comboUpdate' && /Power Slide/.test(e.data.name)).map(e=>e.data);
console.log('Power Slide awards:', ps.map(d=>`${d.name} ${d.pts}pts`).join(', ') || 'none');
